name: Mykola-Popyk-343-Lab5

on:
  workflow_dispatch:

jobs:
  logparser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download logfile
        run: wget https://gitlab.com/oyakivchik/logfile/-/raw/main/access.log

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f Lab5/requirements.txt ]; then pip install -r Lab5/requirements.txt; fi
      - name: Parse logfile
        run:
          python Lab5/log_parser.py access.log

      - name: Send data wia email
        run:
          python Lab5/ip_email.py access_logs.db mykolarpopyk@gmail.com
